### ISSUE TITLE
Issues since upgrading from 2.1.9 -> 2.10.0

### ISSUE THREAD

**Issue by mvarrieur** [xdave/typescript-fsa-redux-thunk#31]
I have a class that wraps creating an action creator to make it a little easier for my project. It basically looks like this:

```ts
import actionCreatorFactory, { ActionCreatorFactory } from 'typescript-fsa';
import asyncFactory, { AsyncWorker } from 'typescript-fsa-redux-thunk';

export default class ActionCreator<ResponseType> {
  private _prefix: string;
  private _creator: ActionCreatorFactory;

  constructor(prefix: string) {
    this._prefix = prefix;
    this._creator = actionCreatorFactory(this._prefix);
  }

  // eslint-disable-next-line @typescript-eslint/explicit-function-return-type, @typescript-eslint/explicit-module-boundary-types
  public asyncAction<ParamsType>({
    type,
    worker,
    commonMeta,
  }: {
    type: string;
    worker: AsyncWorker<ParamsType, unknown, ResponseType, any>;
    commonMeta?: { [key: string]: any } | null | undefined;
  }) {
    return asyncFactory<ResponseType>(this._creator)(type, worker, commonMeta);
  }
}
```

To create an action I'd do something like:
```ts
import ActionCreator from '../utils/ActionCreator';
import { ReturnType, http } from '@company';

export const actionCreatorInstance = new ActionCreator<ReturnType>('foo');

export interface ActionParams {
  config: { [key: string]: string };
  id: string;
}

export const loadStuff = actionCreatorInstance.asyncAction<ActionParams>({
  type: 'LoadOne',
  worker: async (params) => {
    const response = await http.loadStuff(params.id, params.config);

    return response.parsedBody;
  },
});
```

The error I am getting looks like:
```
[ ERROR ]  TypeScript: ./src/components/my-component/my-component.tsx:328:24
Argument of type '{ config: { [key: string]: string }; id: string; }' is not assignable to parameter of type
'ReturnType'. Object literal may only specify known properties, and 'config' does not exist in type 'ReturnType'.
```

It wasn't perfect (couldn't figure out how to make the reducers aware of the return type which I lived with) but it worked.

But, since upgrading to 2.10.0 I started getting errors. Not sure if a return type changed or what, I tried backtracing it but couldn't make heads or tails unfortunately.

I'm thinking something got flipped around where I was passing the params before now it's expecting the return type, but I've tried all the combinations I could think of with no luck so far.

_Note_: I had to change all the type names and everything to prevent leaking company info so there might be a mismatch or two above somewhere.

**Comment by mvarrieur** [comment]
As I note I did notice I think the param order for the worker changed, so I've also tried changing that to `worker: AsyncWorker<ParamsType, ResponseType, unknown, any>;` with no luck.

**Comment by mvarrieur** [comment]
And one last note: if I get everything else seemingly working, it won't accept a normal `Promise<ReturnType>` since switching to `MaybePromise`? Is that intentional?

**Comment by keisukekomeda** [comment]
Hi.
I also have type error since upgrading from 2.1.9 -> 2.10.0.
Seems similar issue. around `MaybePromise` and `PromiseLike`.

```
import actionCreatorFactory from "typescript-fsa";
import asyncFactory from "typescript-fsa-redux-thunk";

const actionCreator = actionCreatorFactory();
const asyncActionCreator = asyncFactory(actionCreator);

export const action = asyncActionCreator<void, void, Error>("action", async () => {
   // blah blah blah...
};

// ~~~ where "dispatch" can be used.
  dispatch(action).catch((err) => {     // Property 'catch' does not exist on type 'PromiseLike<unknown>'.
    // error handling
  }
```

another place.
```
Argument of type 'PromiseLike<Blah>' is not assignable to parameter of type 'Promise<unknown>'.
      Type 'PromiseLike<Blah>' is missing the following properties from type 'Promise<unknown>': catch, [Symbol.toStringTag], finally
```

**Comment by xdave** [comment]
taking a look

**Comment by xdave** [comment]
Yeah recent changes reintroduced PromiseLike in place of Promise... Will revert that part when I get a chance today.

**Comment by xdave** [comment]
@mvarrieur @keisukekomeda I've published 2.10.1
https://www.npmjs.com/package/typescript-fsa-redux-thunk/v/2.10.1

Please take a look and let me know if it's still broken.

**Comment by keisukekomeda** [comment]
@xdave
In my environment, the update fixes the type error and pass all the test.
Thank you very much!

**Comment by mvarrieur** [comment]
Going to check this out tomorrow on my end, thanks for looking into it!

**Comment by mvarrieur** [comment]
Sorry! Got sidetracked and looking at this today.

**Comment by mvarrieur** [comment]
Worked great, big improvement thank you!
